FROM debian:13-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        gdb \
        git \
        valgrind \
        clang \
        clangd \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

CMD ["/bin/bash"]